name: perl
version: 5.005
abstract: Practical Extraction and Reporting Language
author: perl5-porters@perl.org
license: perl
distribution_type: core
private:
  directory:
    - ext/Data/Dumper
    - ext/DB_File
    - lib/CGI
    - lib/CPAN
    - lib/File/Spec

  file:
    - ext/Cwd
    - ext/Devel/PPPort
    - ext/Digest/MD5
    - ext/Encode
    - ext/Filter/t/call.t
    - ext/Filter/Util/Call
    - ext/List/Util
    - ext/MIME/Base64
    - ext/Safe
    - ext/Storable
    - ext/Time/HiRes
    - ext/Unicode/Normalize
    - lib/Attribute/Handlers
    - lib/Attribute/Handlers.pm
    - lib/bigint.pm
    - lib/bignum
    - lib/bignum.pm
    - lib/bigrat.pm
    - lib/CGI.pm
    - lib/Class/ISA
    - lib/Class/ISA.pm
    - lib/CPAN.pm
    - lib/Cwd.pm
    - lib/Digest
    - lib/Digest.pm
    - lib/Digest/base.pm
    - lib/ExtUtils/Command
    - lib/ExtUtils/Command.pm
    - lib/ExtUtils/Install.pm
    - lib/ExtUtils/Installed.pm
    - lib/ExtUtils/Liblist
    - lib/ExtUtils/Liblist.pm
    - lib/ExtUtils/MakeMaker
    - lib/ExtUtils/MakeMaker.pm
    - lib/ExtUtils/Manifest.pm
    - lib/ExtUtils/Mkbootstrap.pm
    - lib/ExtUtils/Mksymlists.pm
    - lib/ExtUtils/MM_OS2.pm
    - lib/ExtUtils/MM_Unix.pm
    - lib/ExtUtils/MM_VMS.pm
    - lib/ExtUtils/MM_Win32.pm
    - lib/ExtUtils/MY.pm
    - lib/ExtUtils/Packlist.pm
    - lib/ExtUtils/t
    - lib/ExtUtils/testlib.pm
    - lib/File/Spec.pm
    - lib/File/Temp
    - lib/File/Temp.pm
    - lib/Filter/Simple
    - lib/Filter/Simple.pm
    - lib/Getopt/Long
    - lib/Getopt/Long.pm
    - lib/I18N/LangTags
    - lib/I18N/LangTags.pm
    - lib/if.pm
    - lib/if.t
    - lib/Locale/Maketext
    - lib/Locale/Maketext.pm
    - lib/Math/BigFloat
    - lib/Math/BigFloat.pm
    - lib/Math/BigInt
    - lib/Math/BigInt.pm
    - lib/Math/BigRat
    - lib/Math/BigRat.pm
    - lib/Memoize
    - lib/Memoize.pm
    - lib/Net/ChangeLog.libnet
    - lib/Net/Cmd.pm
    - lib/Net/Config.pm
    - lib/Net/Domain.pm
    - lib/Net/FTP
    - lib/Net/FTP.pm
    - lib/Net/libnetFAQ.pod
    - lib/Net/Netrc.pm
    - lib/Net/NNTP.pm
    - lib/Net/Ping
    - lib/Net/Ping.pm
    - lib/Net/POP3.pm
    - lib/Net/README.libnet
    - lib/Net/SMTP.pm
    - lib/Net/t
    - lib/Net/Time.pm
    - lib/NEXT
    - lib/NEXT.pm
    - lib/PerlIO/via/QuotedPrint.pm
    - lib/PerlIO/via/t/QuotedPrint.t
    - lib/Pod/Checker.pm
    - lib/Pod/Find.pm
    - lib/Pod/Html.pm
    - lib/Pod/InputObjects.pm
    - lib/Pod/LaTeX.pm
    - lib/Pod/Man.pm
    - lib/Pod/ParseLink.pm
    - lib/Pod/Parser.pm
    - lib/Pod/ParseUtils.pm
    - lib/Pod/Perldoc
    - lib/Pod/Perldoc.pm
    - lib/Pod/PlainText.pm
    - lib/Pod/Select.pm
    - lib/Pod/t/man.t
    - lib/Pod/t/parselink.t
    - lib/Pod/t/pod2latex.t
    - lib/Pod/Text.pm
    - lib/Pod/Text/Color.pm
    - lib/Pod/Text/Overstrike.pm
    - lib/Pod/Text/Termcap.pm
    - lib/Pod/Usage.pm
    - lib/Switch
    - lib/Switch.pm
    - lib/Term/ANSIColor
    - lib/Term/ANSIColor.pm
    - lib/Term/Cap.pm
    - lib/Term/Cap.t
    - lib/Test.pm
    - lib/Test/Builder.pm
    - lib/Test/Harness
    - lib/Test/Harness.pm
    - lib/Test/More.pm
    - lib/Test/Simple
    - lib/Test/Simple.pm
    - lib/Test/t
    - lib/Text/Balanced
    - lib/Text/Balanced.pm
    - lib/Text/Tabs.pm
    - lib/Text/TabsWrap
    - lib/Text/Wrap.pm
    - lib/Tie/File
    - lib/Tie/File.pm
    - lib/Time/Local.pm
    - lib/Time/Local.t
    - lib/Unicode/Collate
    - lib/Unicode/Collate.pm
    - pod/pod2man.PL
    - pod/pod2text.PL
    - pod/pod2usage.PL
    - pod/podchecker.PL
    - pod/podselect.PL
    - t/lib/filter-util.pl
    - t/lib/Filter/Simple
    - t/lib/MakeMaker
    - t/lib/Math
    - t/lib/sample-tests
    - t/lib/Test/Simple
    - t/lib/TieIn.pm
    - t/lib/TieOut.pm
    - t/pod/find.t
    - t/pod/testcmp.pl
    - t/pod/testp2pt.pl
    - t/pod/testpchk.pl

