#!/usr/local/bin/perl -w

my @undo = ();

my $changes = 0;

$^I = ".bak";


while (<>)
 {
  $changes++ if s/fprintf\s*\(\s*(stderr|Perl_debug_log)\s*,\s*/PerlIO_printf($1, /g;
  $changes++ if s/PerlIO_printf\s*\(\s*stderr\s*,\s*/PerlIO_printf(PerlIO_stderr(), /g;
  print;
  if (eof)
   {
    push(@undo,$ARGV) unless ($changes);
    warn "$changes changes in $ARGV\n";
    $changes = 0;
   }
 }

foreach (@undo)
 {
  rename("$_$^I",$_) || die "Cannot rename $_$^I to $_:$!";
 }
